name: ESLint Check (Frontend)

on: [pull_request, push]

jobs:
  lint:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v1
      - uses: a-b-r-o-w-n/eslint-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: "./frontend/src/**/*"
          extensions: ".js,.ts"
          working-directory: "./frontend"
          quiet: "false"